apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: mightycalc-persistence
spec:
  ports:
  - port: 5432
    name: postgres
  clusterIP: None
  selector:
    app: mightycalc-persistence