kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mightycalc-storage
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
  zone: asia-east2-a
  fsType: ext4