version: 0.0.{build}
branches:
  only:
  - master
image: Ubuntu
services:
 - docker
install:
- sh: |
    
    . ./git_versioning.sh

    export APP_VERSION=${version}
    export FILE_VERSION=${fileVersion}
    export INFORMATIONAL_VERSION=${informationVersion}

    echo "exported app version is $APP_VERSION"
    echo "exported file version is $FILE_VERSION"
    echo "exported info version is $INFORMATIONAL_VERSION"

- ps: Update-AppveyorBuild -Version "$env:APP_VERSION+$env:APPVEYOR_BUILD_NUMBER"
build_script:
- sh: |
    set -Eeuxo pipefail
    cd ./src 
    docker build . -f ./buildenv.dockerfile --target=build-env -t aleskov/mightycalc-buildenv:latest -t aleskov/mightycalc-buildenv:$APP_VERSION
    docker build . -f ./buildenv.dockerfile  -t aleskov/mightycalc:latest -t aleskov/mightycalc:$APP_VERSION
    docker save aleskov/mightycalc:latest > mightycalc.tar  
    cd ..
   
    docker build . -f ./build/persistence/persistence.dockerfile -t aleskov/mightycalc-persistence:latest -t aleskov/mightycalc-persistence:$APP_VERSION
test_script:
- sh: |
    set -Eeuxo pipefail
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./MightyCalc.API.Tests/MightyCalc.API.Tests.csproj -c Release --no-build | api_tests.txt; test ${PIPESTATUS[0]} -eq 0
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./MightyCalc.Node.Tests/MightyCalc.Node.Tests.csproj -c Release --no-build | node_tests.txt; test ${PIPESTATUS[0]} -eq 0
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./MightyCalc.Reports.Tests/MightyCalc.Reports.Tests.csproj -c Release --no-build | report_tests.txt; test ${PIPESTATUS[0]} -eq 0
artifacts:
- path: '**\mighty*.tar'
  name: Containers
- path: '**\*_tests.txt'
  name: TestLogs
deploy_script:
- sh: | 
    docker login -u $dockerUser -p $dockerPassword
    docker push aleskov/mightycalc-persistence
    docker push aleskov/mightycalc 
    docker push aleskov/mightycalc-buildenv
