version: 0.0.{build}
branches:
  only:
  - master
image: Ubuntu
services:
 - docker
install:
- sh: |
    
    . ./git_versioning.sh

    export APP_VERSION=${version}
    export FILE_VERSION=${fileVersion}
    export INFORMATIONAL_VERSION=${informationVersion}

    echo "exported app version is $APP_VERSION"
    echo "exported file version is $FILE_VERSION"
    echo "exported info version is $INFORMATIONAL_VERSION"

- ps: Update-AppveyorBuild -Version "$env:APP_VERSION+$env:APPVEYOR_BUILD_NUMBER"
build_script:
- sh: |
    cd ./src 
    docker build . -f ./buildenv.dockerfile -t aleskov/mightycalc-buildenv:latest -t aleskov/mightycalc-buildenv:$APP_VERSION
    cd ..
    docker build . -f ./build/persistence/persistence.dockerfile -t aleskov/mightycalc-persistence:latest -t aleskov/mightycalc-persistence:$APP_VERSION
    docker build . -f ./build/api/runtime.dockerfile -t aleskov/mightycalc:latest -t aleskov/mightycalc:$APP_VERSION
    docker save aleskov/mightycalc > mightycalc.tar   
test_script:
- sh: |
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./src/MightyCalc.API.Tests/MightyCalc.API.Tests.csproj -c Release --no-build 
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./src/MightyCalc.Node.Tests/MightyCalc.Node.Tests.csproj -c Release --no-build
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./src/MightyCalc.Reports.Tests/MightyCalc.Reports.Tests.csproj -c Release --no-build 
artifacts:
- path: '**\mighty*.tar'
  name: Containers
deploy_script:
- sh: |
    echo $dockerUser 
    echo $dockerPassword  
    docker login -u $dockerUser -p $dockerPassword
    #docker push aleskov/mightycalc-buildenv
    docker push aleskov/mightycalc-persistence
    docker push aleskov/mightycalc 
