version: 0.0.{build}
branches:
  only:
  - master
image: Ubuntu
services:
 - docker
install:
- sh: |
    
    . ./build/git_versioning.sh

    export APP_VERSION=${version}
    export FILE_VERSION=${fileVersion}
    export INFORMATIONAL_VERSION=${informationVersion}

    echo "exported app version is $APP_VERSION"
    echo "exported file version is $FILE_VERSION"
    echo "exported info version is $INFORMATIONAL_VERSION"

    curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.27.0/minikube-linux-amd64
    chmod +x minikube
    sudo mv minikube /usr/local/bin/.

    curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.10.0/bin/linux/amd64/kubectl
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/.

- ps: Update-AppveyorBuild -Version "$env:APP_VERSION+$env:APPVEYOR_BUILD_NUMBER"
build_script:
- sh: |
    cd ./src 
    docker build . --target=build-env -t aleskov/mightycalc-buildenv:latest -t aleskov/mightycalc-buildenv:$APP_VERSION
    docker build . -t aleskov/mightycalc:latest -t aleskov/mightycalc:$APP_VERSION
    docker save aleskov/mightycalc:latest > mightycalc.tar  
    cd ..
   
    docker build . -f ./build/persistence/persistence.dockerfile -t aleskov/mightycalc-persistence:latest -t aleskov/mightycalc-persistence:$APP_VERSION
test_script:
- sh: |
    set -euxo pipefail

    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./MightyCalc.API.Tests/MightyCalc.API.Tests.csproj -c Release --no-build > api_tests.txt
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./MightyCalc.Node.Tests/MightyCalc.Node.Tests.csproj -c Release --no-build > node_tests.txt
    docker run --entrypoint dotnet aleskov/mightycalc-buildenv test ./MightyCalc.Reports.Tests/MightyCalc.Reports.Tests.csproj -c Release --no-build > report_tests.txt
  
    kubectl version
    ./deploy/create_environment.sh

    dotnet test ./MightyCalc.Reports.IntegrationTests/MightyCalc.Reports.IntegrationTests.csproj -c Release --no-build > report_tests.txt

artifacts:
- path: '**\mighty*.tar'
  name: Containers
- path: '**\*_tests.txt'
  name: TestLogs
deploy_script:
- sh: | 
    docker login -u $dockerUser -p $dockerPassword
    docker push aleskov/mightycalc-persistence
    docker push aleskov/mightycalc 
