version: 0.0.{build}
branches:
  only:
  - master
image: Ubuntu
environment:
  # Disable Powershell on Linux machines
  #APPVEYOR_YML_DISABLE_PS_LINUX: "true"
  # Changes ownership of minikube config dirs to running user
  CHANGE_MINIKUBE_NONE_USER: "true"
  # Set kubeconfig and minikube paths
  KUBECONFIG: "/home/appveyor/.kube/config"
  MINIKUBE_HOME: "/home/appveyor/kubernetes"
  # Disable prompts for CI
  MINIKUBE_WANTUPDATENOTIFICATION: "false"
  MINIKUBE_WANTREPORTERRORPROMPT: "false"
services:
 - docker
install:
- sh: |
    
    . ./build/git_versioning.sh

    export APP_VERSION=${version}
    export FILE_VERSION=${fileVersion}
    export INFORMATIONAL_VERSION=${informationVersion}

    echo "exported app version is $APP_VERSION"
    echo "exported file version is $FILE_VERSION"
    echo "exported info version is $INFORMATIONAL_VERSION"

    curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.0.0/minikube-linux-amd64
    chmod +x minikube
    sudo mv minikube /usr/local/bin/.

    curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubectl
    chmod +x kubectl
    sudo mv kubectl /usr/local/bin/.
    sudo -E minikube start --vm-driver=none

- ps: Update-AppveyorBuild -Version "$env:APP_VERSION+$env:APPVEYOR_BUILD_NUMBER"
build_script:
- sh: |
    cd ./src 
    docker build . --target=build-env -t mightycalc-test:local
    docker build . -t aleskov/mightycalc:latest -t aleskov/mightycalc:$APP_VERSION
    docker save aleskov/mightycalc:latest > mightycalc.tar  
    cd ..
   
    docker build . -f ./build/persistence/persistence.dockerfile -t aleskov/mightycalc-persistence:latest -t aleskov/mightycalc-persistence:$APP_VERSION
test_script:
- sh: |
    set -e pipefail

    echo running unit tests
    #using docker instead of k8s for simplicity, we don't need any external services
    docker run --entrypoint dotnet mightycalc-test:local test ./MightyCalc.API.Tests/MightyCalc.API.Tests.csproj -c Release --no-build > api_tests.txt
    docker run --entrypoint dotnet mightycalc-test:local test ./MightyCalc.Node.Tests/MightyCalc.Node.Tests.csproj -c Release --no-build > node_tests.txt
    docker run --entrypoint dotnet mightycalc-test:local test ./MightyCalc.Reports.Tests/MightyCalc.Reports.Tests.csproj -c Release --no-build > report_tests.txt
   
    echo creating environment for integration tests
    cd ./deploy
    ./create_environment.sh dd
    #run integration tests in created environment
    
    cd ../test
    ./integration_tests.sh

artifacts:
- path: '**\mighty*.tar'
  name: Containers
- path: '**\*_tests.txt'
  name: TestLogs
deploy_script:
- sh: | 
    docker login -u $dockerUser -p $dockerPassword
    docker push aleskov/mightycalc-persistence
    docker push aleskov/mightycalc 
