apiVersion: v1
kind: Service
metadata:
  name: nodes
spec:
  ports:
  - port: 2555
    name: akka
    protocol: TCP
    targetPort: 2555
  - port: 2556
    name: node-cmd
    protocol: TCP
    targetPort: 2556
  selector:
    type: node
  clusterIP: None