apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
        type: node
    spec:
      containers:
      - name: node
        image: aleskov/mightycalc-node:stable
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        ports:
        - name: akka
          containerPort: 2552
        - name: akka-cmd
          containerPort: 9110
        livenessProbe:
          tcpSocket:
            port: 2552
        env:
        - name: MightyCalc_Journal
          value: "Host=postgres-svc;Port=5432;Database=journal;User ID=postgres;"
        - name: MightyCalc_SnapshotStore
          value: "Host=postgres-svc;Port=5432;Database=snapshotstore;User ID=postgres;"
        - name: MightyCalc_ReadModel
          value: "Host=postgres-svc;Port=5432;Database=readmodel;User ID=postgres;"
        - name: MightyCalc_NodePort
          value: "2552"
        - name: MightyCalc_CmdPort
          value: "9110"
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name 
        - name: HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: MightyCalc_HostName
          value: "$(HOST_IP)"
        - name: MightyCalc_PublicHostName
          value: "$(HOST_IP)"
        - name: MightyCalc_SeedNodes
          value: "akka.tcp://MightyCalc@seed-0.seeds:2552"
        - name: MightyCalc_NodeRoles
          value: "projection calculation"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      terminationGracePeriodSeconds: 10
