// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MightyCalc.Reports;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace MightyCalc.Reports.Migrations
{
    [DbContext(typeof(FunctionUsageContext))]
    [Migration("20190314181819_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("MightyCalc.Reports.FunctionUsage", b =>
                {
                    b.Property<string>("CalculatorName");

                    b.Property<string>("FunctionName");

                    b.Property<int>("InvocationsCount");

                    b.HasKey("CalculatorName", "FunctionName");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("MightyCalc.Reports.Projections", b =>
                {
                    b.Property<string>("Name");

                    b.Property<string>("Event");

                    b.Property<int>("Sequence");

                    b.HasKey("Name", "Event");

                    b.ToTable("Projections");
                });
#pragma warning restore 612, 618
        }
    }
}
