apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mightycalc-deploy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: mightycalc
    spec:
      containers:
      - name: mightycalc-container
        image: aleskov/mightycalc
        imagePullPolicy: Always
        env:
        - name: namespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: podname
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: nodename
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - name: http
          containerPort: 80
      terminationGracePeriodSeconds: 600
