apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: api
  labels:
    app: api
    type: node
spec:
  serviceName: nodes
  replicas: 1 
  selector:
    matchLabels:
      app: api # has to match .spec.template.metadata.labels
      type: node
  template:
    metadata:
      labels:
        app: api # has to match .spec.selector.matchLabels
        type: node
    spec:
      terminationGracePeriodSeconds: 35
      containers:
      - name: node
        image: aleskov/mightycalc-api:stable
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "pbm 127.0.0.1:9110 cluster leave"]
        ports:
        - name: akka
          containerPort: 2552
          protocol: TCP
        - name: http
          containerPort: 80
        - name: akka-cmd
          containerPort: 9110
          protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 2552
        env:
        - name: MightyCalc_ReadModel
          value: "Host=postgres-svc;Port=5432;Database=readmodel;User ID=postgres;"
        - name: MightyCalc_NodePort
          value: "2552"
        - name: MightyCalc_CmdPort
          value: "9110"
        - name: MightyCalc_HostName
          value: "0.0.0.0"
        - name: HOST_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MightyCalc_PublicHostName
          value: "$(HOST_NAME).nodes"
        - name: MightyCalc_SeedNodes
          value: "akka.tcp://MightyCalc@seed-0.nodes:2552"
        - name: MightyCalc_NodeRoles
          value: "api"
       
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"